# Generated by Django 5.2.3 on 2025-06-14 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Standup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('slack_thread_ts', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standups', to='teams.team')),
            ],
            options={
                'ordering': ['-date', 'team__name'],
                'unique_together': {('team', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StandupReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('initial', 'Initial Reminder'), ('follow_up', 'Follow-up Reminder'), ('final', 'Final Reminder')], max_length=15)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('slack_message_ts', models.CharField(blank=True, max_length=50, null=True)),
                ('responded', models.BooleanField(default=False)),
                ('standup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='standups.standup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='StandupMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_members', models.IntegerField()),
                ('responses_count', models.IntegerField()),
                ('completion_rate', models.FloatField()),
                ('average_response_time', models.DurationField(blank=True, null=True)),
                ('first_response_time', models.TimeField(blank=True, null=True)),
                ('last_response_time', models.TimeField(blank=True, null=True)),
                ('mood_distribution', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='teams.team')),
            ],
            options={
                'ordering': ['-date', 'team__name'],
                'unique_together': {('team', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StandupResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yesterday_work', models.TextField(help_text='What did you work on yesterday?')),
                ('today_work', models.TextField(help_text='What will you work on today?')),
                ('blockers', models.TextField(blank=True, help_text='Are there any blockers or impediments?')),
                ('mood', models.CharField(choices=[('great', '😄 Great'), ('good', '😊 Good'), ('okay', '😐 Okay'), ('stressed', '😰 Stressed'), ('blocked', '😤 Blocked')], default='good', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slack_message_ts', models.CharField(blank=True, max_length=50, null=True)),
                ('standup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='standups.standup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('standup', 'user')},
            },
        ),
    ]
