services:
  # PostgreSQL Database
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: standapp_db
      POSTGRES_USER: standapp_user
      POSTGRES_PASSWORD: standapp_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U standapp_user -d standapp_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (Message Broker)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Backend
  backend:
    build: .
    command: gunicorn standapp.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    expose:
      - "8000"
    environment:
      - DEBUG=0
      - DB_NAME=standapp_db
      - DB_USER=standapp_user
      - DB_PASSWORD=standapp_password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,backend,nginx
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # React Frontend
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - "3000"
    environment:
      - REACT_APP_API_URL=http://localhost/api
    depends_on:
      - backend

  # Nginx Proxy Server
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  redis_data: