# Generated by Django 5.2.3 on 2025-06-14 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standups', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50, unique=True)),
                ('team_name', models.CharField(max_length=100)),
                ('bot_user_id', models.CharField(max_length=50)),
                ('bot_access_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['team_name'],
            },
        ),
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('message_ts', models.CharField(max_length=50, unique=True)),
                ('thread_ts', models.CharField(blank=True, max_length=50, null=True)),
                ('message_type', models.CharField(choices=[('reminder', 'Stand-up Reminder'), ('summary', 'Stand-up Summary'), ('follow_up', 'Follow-up Reminder'), ('response', 'Stand-up Response'), ('notification', 'Notification')], max_length=15)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('standup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standups.standup')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack_integration.slackworkspace')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SlackInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('interaction_type', models.CharField(choices=[('button_click', 'Button Click'), ('modal_submission', 'Modal Submission'), ('slash_command', 'Slash Command'), ('message_action', 'Message Action')], max_length=20)),
                ('trigger_id', models.CharField(blank=True, max_length=100, null=True)),
                ('callback_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('standup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standups.standup')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack_integration.slackworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlackUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=50, unique=True)),
                ('slack_username', models.CharField(max_length=100)),
                ('slack_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack_integration.slackworkspace')),
            ],
            options={
                'ordering': ['user__username'],
                'unique_together': {('slack_user_id', 'workspace')},
            },
        ),
        migrations.CreateModel(
            name='SlackChannelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50)),
                ('channel_name', models.CharField(max_length=100)),
                ('is_private', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack_integration.slackworkspace')),
            ],
            options={
                'ordering': ['team__name'],
                'unique_together': {('channel_id', 'workspace')},
            },
        ),
    ]
